/Projects/Agus/ITA/.bender/git/checkouts/common_verification-2d4a75665ce644a6/test/tb_clk_rst_gen.sv
/Projects/Agus/ITA/.bender/git/checkouts/tech_cells_generic-55fa3871c0dd2458/src/rtl/tc_sram.sv
/Projects/Agus/ITA/.bender/git/checkouts/tech_cells_generic-55fa3871c0dd2458/src/rtl/tc_sram_impl.sv
/Projects/Agus/ITA/.bender/git/checkouts/tech_cells_generic-55fa3871c0dd2458/src/rtl/tc_clk.sv
/Projects/Agus/ITA/.bender/git/checkouts/tech_cells_generic-55fa3871c0dd2458/src/deprecated/cluster_pwr_cells.sv
/Projects/Agus/ITA/.bender/git/checkouts/tech_cells_generic-55fa3871c0dd2458/src/deprecated/generic_memory.sv
/Projects/Agus/ITA/.bender/git/checkouts/tech_cells_generic-55fa3871c0dd2458/src/deprecated/generic_rom.sv
/Projects/Agus/ITA/.bender/git/checkouts/tech_cells_generic-55fa3871c0dd2458/src/deprecated/pad_functional.sv
/Projects/Agus/ITA/.bender/git/checkouts/tech_cells_generic-55fa3871c0dd2458/src/deprecated/pulp_buffer.sv
/Projects/Agus/ITA/.bender/git/checkouts/tech_cells_generic-55fa3871c0dd2458/src/deprecated/pulp_pwr_cells.sv
/Projects/Agus/ITA/.bender/git/checkouts/tech_cells_generic-55fa3871c0dd2458/src/tc_pwr.sv
/Projects/Agus/ITA/.bender/git/checkouts/tech_cells_generic-55fa3871c0dd2458/test/tb_tc_sram.sv
/Projects/Agus/ITA/.bender/git/checkouts/tech_cells_generic-55fa3871c0dd2458/src/deprecated/pulp_clock_gating_async.sv
/Projects/Agus/ITA/.bender/git/checkouts/tech_cells_generic-55fa3871c0dd2458/src/deprecated/cluster_clk_cells.sv
/Projects/Agus/ITA/.bender/git/checkouts/tech_cells_generic-55fa3871c0dd2458/src/deprecated/pulp_clk_cells.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/binary_to_gray.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/cb_filter_pkg.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/cc_onehot.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/cdc_reset_ctrlr_pkg.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/cf_math_pkg.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/clk_int_div.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/credit_counter.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/delta_counter.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/ecc_pkg.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/edge_propagator_tx.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/exp_backoff.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/fifo_v3.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/gray_to_binary.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/isochronous_4phase_handshake.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/isochronous_spill_register.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/lfsr.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/lfsr_16bit.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/lfsr_8bit.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/lossy_valid_to_stream.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/mv_filter.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/onehot_to_bin.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/plru_tree.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/passthrough_stream_fifo.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/popcount.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/rr_arb_tree.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/rstgen_bypass.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/serial_deglitch.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/shift_reg.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/shift_reg_gated.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/spill_register_flushable.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/stream_demux.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/stream_filter.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/stream_fork.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/stream_intf.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/stream_join_dynamic.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/stream_mux.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/stream_throttle.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/sub_per_hash.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/sync.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/sync_wedge.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/unread.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/read.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/addr_decode_dync.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/cdc_2phase.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/cdc_4phase.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/clk_int_div_static.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/addr_decode.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/addr_decode_napot.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/multiaddr_decode.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/cb_filter.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/cdc_fifo_2phase.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/clk_mux_glitch_free.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/counter.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/ecc_decode.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/ecc_encode.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/edge_detect.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/lzc.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/max_counter.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/rstgen.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/spill_register.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/stream_delay.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/stream_fifo.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/stream_fork_dynamic.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/stream_join.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/cdc_reset_ctrlr.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/cdc_fifo_gray.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/fall_through_register.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/id_queue.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/stream_to_mem.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/stream_arbiter_flushable.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/stream_fifo_optimal_wrap.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/stream_register.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/stream_xbar.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/cdc_fifo_gray_clearable.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/cdc_2phase_clearable.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/mem_to_banks_detailed.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/stream_arbiter.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/stream_omega_net.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/mem_to_banks.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/test/addr_decode_tb.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/test/cb_filter_tb.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/test/cdc_2phase_tb.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/test/cdc_2phase_clearable_tb.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/test/cdc_fifo_tb.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/test/cdc_fifo_clearable_tb.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/test/fifo_tb.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/test/graycode_tb.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/test/id_queue_tb.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/test/passthrough_stream_fifo_tb.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/test/popcount_tb.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/test/rr_arb_tree_tb.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/test/stream_test.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/test/stream_register_tb.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/test/stream_to_mem_tb.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/test/sub_per_hash_tb.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/test/isochronous_crossing_tb.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/test/stream_omega_net_tb.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/test/stream_xbar_tb.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/test/clk_int_div_tb.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/test/clk_int_div_static_tb.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/test/clk_mux_glitch_free_tb.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/test/lossy_valid_to_stream_tb.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/deprecated/clock_divider_counter.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/deprecated/clk_div.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/deprecated/find_first_one.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/deprecated/generic_LFSR_8bit.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/deprecated/generic_fifo.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/deprecated/prioarbiter.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/deprecated/pulp_sync.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/deprecated/pulp_sync_wedge.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/deprecated/rrarbiter.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/deprecated/clock_divider.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/deprecated/fifo_v2.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/deprecated/fifo_v1.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/edge_propagator_ack.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/edge_propagator.sv
/Projects/Agus/ITA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/edge_propagator_rx.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/tcdm_interconnect/tcdm_interconnect_pkg.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/tcdm_interconnect/addr_dec_resp_mux.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/tcdm_interconnect/amo_shim.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/variable_latency_interconnect/addr_decoder.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/tcdm_interconnect/xbar.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/variable_latency_interconnect/simplex_xbar.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/tcdm_interconnect/clos_net.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/tcdm_interconnect/bfly_net.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/variable_latency_interconnect/full_duplex_xbar.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/tcdm_interconnect/tcdm_interconnect.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/variable_latency_interconnect/variable_latency_bfly_net.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/variable_latency_interconnect/variable_latency_interconnect.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/low_latency_interco/FanInPrimitive_Req.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/low_latency_interco/ArbitrationTree.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/low_latency_interco/MUX2_REQ.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/low_latency_interco/AddressDecoder_Resp.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/low_latency_interco/TestAndSet.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/low_latency_interco/RequestBlock2CH.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/low_latency_interco/RequestBlock1CH.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/low_latency_interco/FanInPrimitive_Resp.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/low_latency_interco/ResponseTree.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/low_latency_interco/ResponseBlock.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/low_latency_interco/AddressDecoder_Req.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/low_latency_interco/XBAR_TCDM.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/low_latency_interco/XBAR_TCDM_WRAPPER.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/low_latency_interco/TCDM_PIPE_REQ.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/low_latency_interco/TCDM_PIPE_RESP.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/low_latency_interco/grant_mask.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/low_latency_interco/priority_Flag_Req.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/peripheral_interco/AddressDecoder_PE_Req.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/peripheral_interco/AddressDecoder_Resp_PE.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/peripheral_interco/ArbitrationTree_PE.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/peripheral_interco/FanInPrimitive_Req_PE.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/peripheral_interco/RR_Flag_Req_PE.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/peripheral_interco/MUX2_REQ_PE.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/peripheral_interco/FanInPrimitive_PE_Resp.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/peripheral_interco/RequestBlock1CH_PE.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/peripheral_interco/RequestBlock2CH_PE.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/peripheral_interco/ResponseBlock_PE.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/peripheral_interco/ResponseTree_PE.sv
/Projects/Agus/ITA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/peripheral_interco/XBAR_PE.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/hwpe_stream_interfaces.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/hwpe_stream_package.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/basic/hwpe_stream_assign.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/basic/hwpe_stream_buffer.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/basic/hwpe_stream_demux_static.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/basic/hwpe_stream_deserialize.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/basic/hwpe_stream_fence.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/basic/hwpe_stream_merge.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/basic/hwpe_stream_mux_static.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/basic/hwpe_stream_serialize.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/basic/hwpe_stream_split.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/fifo/hwpe_stream_fifo_ctrl.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/fifo/hwpe_stream_fifo_scm.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/streamer/hwpe_stream_addressgen.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/streamer/hwpe_stream_addressgen_v2.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/streamer/hwpe_stream_addressgen_v3.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/streamer/hwpe_stream_sink_realign.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/streamer/hwpe_stream_source_realign.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/streamer/hwpe_stream_strbgen.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/streamer/hwpe_stream_streamer_queue.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/tcdm/hwpe_stream_tcdm_assign.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/tcdm/hwpe_stream_tcdm_mux.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/tcdm/hwpe_stream_tcdm_mux_static.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/tcdm/hwpe_stream_tcdm_reorder.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/tcdm/hwpe_stream_tcdm_reorder_static.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/fifo/hwpe_stream_fifo_earlystall.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/fifo/hwpe_stream_fifo_earlystall_sidech.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/fifo/hwpe_stream_fifo_scm_test_wrap.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/fifo/hwpe_stream_fifo_sidech.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/fifo/hwpe_stream_fifo.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/tcdm/hwpe_stream_tcdm_fifo_load_sidech.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/fifo/hwpe_stream_fifo_passthrough.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/streamer/hwpe_stream_source.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/tcdm/hwpe_stream_tcdm_fifo.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/tcdm/hwpe_stream_tcdm_fifo_load.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/tcdm/hwpe_stream_tcdm_fifo_store.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/streamer/hwpe_stream_sink.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/verif/hwpe_stream_traffic_gen.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/verif/hwpe_stream_traffic_recv.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/verif/tb_fifo.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/l2_tcdm_demux.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/lint_2_apb.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/lint_2_axi.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/axi_2_lint/axi64_2_lint32.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/axi_2_lint/axi_read_ctrl.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/axi_2_lint/axi_write_ctrl.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/axi_2_lint/lint64_to_32.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/XBAR_L2/AddressDecoder_Req_L2.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/XBAR_L2/AddressDecoder_Resp_L2.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/XBAR_L2/ArbitrationTree_L2.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/XBAR_L2/FanInPrimitive_Req_L2.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/XBAR_L2/FanInPrimitive_Resp_L2.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/XBAR_L2/MUX2_REQ_L2.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/XBAR_L2/RequestBlock_L2_1CH.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/XBAR_L2/RequestBlock_L2_2CH.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/XBAR_L2/ResponseBlock_L2.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/XBAR_L2/ResponseTree_L2.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/XBAR_L2/RR_Flag_Req_L2.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/XBAR_L2/XBAR_L2.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/XBAR_BRIDGE/AddressDecoder_Req_BRIDGE.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/XBAR_BRIDGE/AddressDecoder_Resp_BRIDGE.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/XBAR_BRIDGE/ArbitrationTree_BRIDGE.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/XBAR_BRIDGE/FanInPrimitive_Req_BRIDGE.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/XBAR_BRIDGE/FanInPrimitive_Resp_BRIDGE.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/XBAR_BRIDGE/MUX2_REQ_BRIDGE.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/XBAR_BRIDGE/RequestBlock1CH_BRIDGE.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/XBAR_BRIDGE/RequestBlock2CH_BRIDGE.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/XBAR_BRIDGE/ResponseBlock_BRIDGE.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/XBAR_BRIDGE/ResponseTree_BRIDGE.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/XBAR_BRIDGE/RR_Flag_Req_BRIDGE.sv
/Projects/Agus/ITA/.bender/git/checkouts/l2_tcdm_hybrid_interco-b72bbb714e0dc5a5/RTL/XBAR_BRIDGE/XBAR_BRIDGE.sv
/Projects/Agus/ITA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/common/hci_package.sv
/Projects/Agus/ITA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/common/hci_interfaces.sv
/Projects/Agus/ITA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/core/hci_core_assign.sv
/Projects/Agus/ITA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/core/hci_core_fifo.sv
/Projects/Agus/ITA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/core/hci_core_mux_dynamic.sv
/Projects/Agus/ITA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/core/hci_core_mux_static.sv
/Projects/Agus/ITA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/core/hci_core_mux_ooo.sv
/Projects/Agus/ITA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/core/hci_core_r_valid_filter.sv
/Projects/Agus/ITA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/core/hci_core_r_id_filter.sv
/Projects/Agus/ITA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/core/hci_core_source.sv
/Projects/Agus/ITA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/core/hci_core_split.sv
/Projects/Agus/ITA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/interco/hci_log_interconnect.sv
/Projects/Agus/ITA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/interco/hci_log_interconnect_l2.sv
/Projects/Agus/ITA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/interco/hci_new_log_interconnect.sv
/Projects/Agus/ITA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/interco/hci_arbiter.sv
/Projects/Agus/ITA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/interco/hci_router_reorder.sv
/Projects/Agus/ITA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/core/hci_core_sink.sv
/Projects/Agus/ITA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/interco/hci_router.sv
/Projects/Agus/ITA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/hci_interconnect.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-ctrl-b4d268c729c1adb1/rtl/hwpe_ctrl_interfaces.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-ctrl-b4d268c729c1adb1/rtl/hwpe_ctrl_package.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-ctrl-b4d268c729c1adb1/rtl/hwpe_ctrl_regfile_ff.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-ctrl-b4d268c729c1adb1/rtl/hwpe_ctrl_regfile_latch.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-ctrl-b4d268c729c1adb1/rtl/hwpe_ctrl_seq_mult.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-ctrl-b4d268c729c1adb1/rtl/hwpe_ctrl_uloop.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-ctrl-b4d268c729c1adb1/rtl/hwpe_ctrl_regfile_latch_test_wrap.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-ctrl-b4d268c729c1adb1/rtl/hwpe_ctrl_regfile.sv
/Projects/Agus/ITA/.bender/git/checkouts/hwpe-ctrl-b4d268c729c1adb1/rtl/hwpe_ctrl_slave.sv
/Projects/Agus/ITA/.bender/git/checkouts/scm-a479c2e455a7e638/latch_scm/register_file_1r_1w_test_wrap.sv
/Projects/Agus/ITA/.bender/git/checkouts/scm-a479c2e455a7e638/latch_scm/register_file_1w_64b_multi_port_read_32b_1row.sv
/Projects/Agus/ITA/.bender/git/checkouts/scm-a479c2e455a7e638/latch_scm/register_file_1w_multi_port_read_1row.sv
/Projects/Agus/ITA/.bender/git/checkouts/scm-a479c2e455a7e638/latch_scm/register_file_1r_1w_all.sv
/Projects/Agus/ITA/.bender/git/checkouts/scm-a479c2e455a7e638/latch_scm/register_file_1r_1w_all_test_wrap.sv
/Projects/Agus/ITA/.bender/git/checkouts/scm-a479c2e455a7e638/latch_scm/register_file_1r_1w_be.sv
/Projects/Agus/ITA/.bender/git/checkouts/scm-a479c2e455a7e638/latch_scm/register_file_1r_1w.sv
/Projects/Agus/ITA/.bender/git/checkouts/scm-a479c2e455a7e638/latch_scm/register_file_1r_1w_1row.sv
/Projects/Agus/ITA/.bender/git/checkouts/scm-a479c2e455a7e638/latch_scm/register_file_1w_128b_multi_port_read_32b.sv
/Projects/Agus/ITA/.bender/git/checkouts/scm-a479c2e455a7e638/latch_scm/register_file_1w_64b_multi_port_read_32b.sv
/Projects/Agus/ITA/.bender/git/checkouts/scm-a479c2e455a7e638/latch_scm/register_file_1w_64b_1r_32b.sv
/Projects/Agus/ITA/.bender/git/checkouts/scm-a479c2e455a7e638/latch_scm/register_file_1w_multi_port_read_be.sv
/Projects/Agus/ITA/.bender/git/checkouts/scm-a479c2e455a7e638/latch_scm/register_file_1w_multi_port_read.sv
/Projects/Agus/ITA/.bender/git/checkouts/scm-a479c2e455a7e638/latch_scm/register_file_2r_1w_asymm.sv
/Projects/Agus/ITA/.bender/git/checkouts/scm-a479c2e455a7e638/latch_scm/register_file_2r_1w_asymm_test_wrap.sv
/Projects/Agus/ITA/.bender/git/checkouts/scm-a479c2e455a7e638/latch_scm/register_file_2r_2w.sv
/Projects/Agus/ITA/.bender/git/checkouts/scm-a479c2e455a7e638/latch_scm/register_file_3r_2w.sv
/Projects/Agus/ITA/.bender/git/checkouts/scm-a479c2e455a7e638/latch_scm/register_file_3r_2w_be.sv
/Projects/Agus/ITA/.bender/git/checkouts/scm-a479c2e455a7e638/latch_scm/register_file_multi_way_1w_64b_multi_port_read_32b.sv
/Projects/Agus/ITA/.bender/git/checkouts/scm-a479c2e455a7e638/latch_scm/register_file_multi_way_1w_multi_port_read.sv
/Projects/Agus/ITA/src/ita_package.sv
/Projects/Agus/ITA/src/ita_accumulator.sv
/Projects/Agus/ITA/src/ita_controller.sv
/Projects/Agus/ITA/src/ita_dotp.sv
/Projects/Agus/ITA/src/ita_fifo_controller.sv
/Projects/Agus/ITA/src/ita_inp1_mux.sv
/Projects/Agus/ITA/src/ita_inp2_mux.sv
/Projects/Agus/ITA/src/ita_input_sampler.sv
/Projects/Agus/ITA/src/ita_output_controller.sv
/Projects/Agus/ITA/src/ita_register_file_1w_1r_double_width_write.sv
/Projects/Agus/ITA/src/ita_register_file_1w_multi_port_read.sv
/Projects/Agus/ITA/src/ita_register_file_1w_multi_port_read_we.sv
/Projects/Agus/ITA/src/ita_requantizer.sv
/Projects/Agus/ITA/src/ita_serdiv.sv
/Projects/Agus/ITA/src/ita_softmax.sv
/Projects/Agus/ITA/src/ita_softmax_top.sv
/Projects/Agus/ITA/src/ita_sumdotp.sv
/Projects/Agus/ITA/src/ita_weight_controller.sv
/Projects/Agus/ITA/src/ita.sv
/Projects/Agus/ITA/src/ita_max_finder.sv
/Projects/Agus/ITA/src/ita_gelu.sv
/Projects/Agus/ITA/src/ita_relu.sv
/Projects/Agus/ITA/src/ita_activation.sv
/Projects/Agus/ITA/src/ita_requantization_controller.sv
/Projects/Agus/ITA/src/tb/ita_tb.sv
/Projects/Agus/ITA/src/tb/clk_rst_gen.sv
/Projects/Agus/ITA/src/tb/rst_gen.sv
/Projects/Agus/ITA/src/tb/activation_tb.sv
/Projects/Agus/ITA/src/hwpe/tb/tb_dummy_memory.sv
/Projects/Agus/ITA/src/hwpe/tb/ita_hwpe_tb.sv

