set_property SRC_FILE_INFO {cfile:/home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_zynq_ultra_ps_e_0_0/DMA_LED_zynq_ultra_ps_e_0_0.xdc rfile:../../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_zynq_ultra_ps_e_0_0/DMA_LED_zynq_ultra_ps_e_0_0.xdc id:1 order:EARLY scoped_inst:zynq_ultra_ps_e_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_1/bd_9be7_psr_aclk_0.xdc rfile:../../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_1/bd_9be7_psr_aclk_0.xdc id:2 order:EARLY scoped_inst:smartconnect_0/inst/clk_map/psr_aclk/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_proc_sys_reset_0_0/DMA_LED_proc_sys_reset_0_0.xdc rfile:../../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_proc_sys_reset_0_0/DMA_LED_proc_sys_reset_0_0.xdc id:3 order:EARLY scoped_inst:proc_sys_reset_0/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_axi_dma_0_0/DMA_LED_axi_dma_0_0.xdc rfile:../../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_axi_dma_0_0/DMA_LED_axi_dma_0_0.xdc id:4 order:EARLY scoped_inst:axi_dma_0/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.runs/DMA_LED_synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:5} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:6 order:LATE scoped_inst:smartconnect_0/inst/m00_exit_pipeline/m00_exit/inst/xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:7 order:LATE scoped_inst:smartconnect_0/inst/m00_nodes/m00_ar_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:8 order:LATE scoped_inst:smartconnect_0/inst/m00_nodes/m00_ar_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:9 order:LATE scoped_inst:smartconnect_0/inst/m00_nodes/m00_aw_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:10 order:LATE scoped_inst:smartconnect_0/inst/m00_nodes/m00_aw_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:11 order:LATE scoped_inst:smartconnect_0/inst/m00_nodes/m00_b_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:12 order:LATE scoped_inst:smartconnect_0/inst/m00_nodes/m00_b_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:13 order:LATE scoped_inst:smartconnect_0/inst/m00_nodes/m00_r_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:14 order:LATE scoped_inst:smartconnect_0/inst/m00_nodes/m00_r_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:15 order:LATE scoped_inst:smartconnect_0/inst/m00_nodes/m00_w_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:16 order:LATE scoped_inst:smartconnect_0/inst/m00_nodes/m00_w_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:17 order:LATE scoped_inst:smartconnect_0/inst/s00_entry_pipeline/s00_mmu/inst/xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:18 order:LATE scoped_inst:smartconnect_0/inst/s00_entry_pipeline/s00_si_converter/inst/xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:19 order:LATE scoped_inst:smartconnect_0/inst/s00_entry_pipeline/s00_transaction_regulator/inst/xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:20 order:LATE scoped_inst:smartconnect_0/inst/s00_nodes/s00_ar_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:21 order:LATE scoped_inst:smartconnect_0/inst/s00_nodes/s00_ar_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:22 order:LATE scoped_inst:smartconnect_0/inst/s00_nodes/s00_r_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:23 order:LATE scoped_inst:smartconnect_0/inst/s00_nodes/s00_r_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:24 order:LATE scoped_inst:smartconnect_0/inst/s01_entry_pipeline/s01_mmu/inst/xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:25 order:LATE scoped_inst:smartconnect_0/inst/s01_entry_pipeline/s01_si_converter/inst/xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:26 order:LATE scoped_inst:smartconnect_0/inst/s01_entry_pipeline/s01_transaction_regulator/inst/xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:27 order:LATE scoped_inst:smartconnect_0/inst/s01_nodes/s01_aw_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:28 order:LATE scoped_inst:smartconnect_0/inst/s01_nodes/s01_aw_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:29 order:LATE scoped_inst:smartconnect_0/inst/s01_nodes/s01_b_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:30 order:LATE scoped_inst:smartconnect_0/inst/s01_nodes/s01_b_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:31 order:LATE scoped_inst:smartconnect_0/inst/s01_nodes/s01_w_node/inst/m_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_async_rst.tcl id:32 order:LATE scoped_inst:smartconnect_0/inst/s01_nodes/s01_w_node/inst/s_sc_xpm_cdc_async_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_sync_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_sync_rst.tcl id:33 order:LATE scoped_inst:axis_data_fifo_0/inst/gen_fifo.xpm_fifo_axis_inst/gaxis_rst_sync.xpm_cdc_sync_rst_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_sync_rst.tcl rfile:../../../../../../../../Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_sync_rst.tcl id:34 order:LATE scoped_inst:axis_data_fifo_1/inst/gen_fifo.xpm_fifo_axis_inst/gaxis_rst_sync.xpm_cdc_sync_rst_inst unmanaged:yes} [current_design]
current_instance zynq_ultra_ps_e_0/inst
set_property src_info {type:SCOPED_XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name clk_pl_0 [get_pins {PS8_i/PLCLK[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells PS8_i]
current_instance
set_property src_info {type:SCOPED_XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins [list smartconnect_0/inst/clk_map/psr_aclk/U0/EXT_LPF/ACTIVE_LOW_AUX.ACT_LO_AUX/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to/D smartconnect_0/inst/clk_map/psr_aclk/U0/EXT_LPF/ACTIVE_LOW_EXT.ACT_LO_EXT/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to/D]]
set_property src_info {type:SCOPED_XDC file:3 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins [list proc_sys_reset_0/U0/EXT_LPF/ACTIVE_LOW_AUX.ACT_LO_AUX/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to/D proc_sys_reset_0/U0/EXT_LPF/ACTIVE_LOW_EXT.ACT_LO_EXT/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to/D]]
set_property src_info {type:SCOPED_XDC file:4 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins [list axi_dma_0/U0/I_RST_MODULE/REG_HRD_RST/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to/D axi_dma_0/U0/I_RST_MODULE/REG_HRD_RST_OUT/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to/D]]
set_property src_info {type:XDC file:5 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells zynq_ultra_ps_e_0/inst]
set_property src_info {type:XDC file:5 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells axi_dma_0/U0]
set_property src_info {type:XDC file:5 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells proc_sys_reset_0/U0]
set_property src_info {type:XDC file:5 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0/inst]
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins smartconnect_0/inst/m00_exit_pipeline/m00_exit/inst/xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:7 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins smartconnect_0/inst/m00_nodes/m00_ar_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:8 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins smartconnect_0/inst/m00_nodes/m00_ar_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:9 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins smartconnect_0/inst/m00_nodes/m00_aw_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:10 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins smartconnect_0/inst/m00_nodes/m00_aw_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:11 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins smartconnect_0/inst/m00_nodes/m00_b_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:12 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins smartconnect_0/inst/m00_nodes/m00_b_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:13 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins smartconnect_0/inst/m00_nodes/m00_r_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:14 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins smartconnect_0/inst/m00_nodes/m00_r_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:15 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins smartconnect_0/inst/m00_nodes/m00_w_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:16 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins smartconnect_0/inst/m00_nodes/m00_w_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:17 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins smartconnect_0/inst/s00_entry_pipeline/s00_mmu/inst/xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:18 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins smartconnect_0/inst/s00_entry_pipeline/s00_si_converter/inst/xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:19 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins smartconnect_0/inst/s00_entry_pipeline/s00_transaction_regulator/inst/xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:20 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins smartconnect_0/inst/s00_nodes/s00_ar_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:21 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins smartconnect_0/inst/s00_nodes/s00_ar_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:22 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins smartconnect_0/inst/s00_nodes/s00_r_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:23 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins smartconnect_0/inst/s00_nodes/s00_r_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:24 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins smartconnect_0/inst/s01_entry_pipeline/s01_mmu/inst/xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:25 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins smartconnect_0/inst/s01_entry_pipeline/s01_si_converter/inst/xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:26 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins smartconnect_0/inst/s01_entry_pipeline/s01_transaction_regulator/inst/xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:27 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins smartconnect_0/inst/s01_nodes/s01_aw_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:28 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins smartconnect_0/inst/s01_nodes/s01_aw_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:29 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins smartconnect_0/inst/s01_nodes/s01_b_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:30 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins smartconnect_0/inst/s01_nodes/s01_b_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:31 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins smartconnect_0/inst/s01_nodes/s01_w_node/inst/m_sc_xpm_cdc_async_rst_inst/src_arst]
set_property src_info {type:SCOPED_XDC file:32 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -through [get_pins smartconnect_0/inst/s01_nodes/s01_w_node/inst/s_sc_xpm_cdc_async_rst_inst/src_arst]
current_instance axis_data_fifo_0/inst/gen_fifo.xpm_fifo_axis_inst/gaxis_rst_sync.xpm_cdc_sync_rst_inst
set_property src_info {type:SCOPED_XDC file:33 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -to [get_cells {syncstages_ff_reg[0]}]
current_instance
current_instance axis_data_fifo_1/inst/gen_fifo.xpm_fifo_axis_inst/gaxis_rst_sync.xpm_cdc_sync_rst_inst
set_property src_info {type:SCOPED_XDC file:34 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -to [get_cells {syncstages_ff_reg[0]}]
current_instance
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells zynq_ultra_ps_e_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells axi_dma_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells proc_sys_reset_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells xlconcat_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells axi_interconnect_0/xbar]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells axi_interconnect_0/s00_couplers/auto_pc]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells axi_interconnect_0/s01_couplers/auto_pc]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells axi_interconnect_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells xlconstant_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells xlconstant_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells xlslice_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells axis_data_fifo_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells axis_data_fifo_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells ITA_AXI_WRAPPER_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0/inst/m00_nodes/m00_ar_node/inst/m_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0/inst/m00_nodes/m00_aw_node/inst/m_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0/inst/m00_nodes/m00_b_node/inst/m_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0/inst/m00_nodes/m00_r_node/inst/m_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0/inst/m00_nodes/m00_w_node/inst/m_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0/inst/s00_nodes/s00_ar_node/inst/m_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0/inst/s00_nodes/s00_r_node/inst/m_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0/inst/s01_nodes/s01_aw_node/inst/m_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0/inst/s01_nodes/s01_b_node/inst/m_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0/inst/s01_nodes/s01_w_node/inst/m_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0/inst/m00_nodes/m00_ar_node/inst/s_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0/inst/m00_nodes/m00_aw_node/inst/s_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0/inst/m00_nodes/m00_b_node/inst/s_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0/inst/m00_nodes/m00_r_node/inst/s_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0/inst/m00_nodes/m00_w_node/inst/s_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0/inst/s00_nodes/s00_ar_node/inst/s_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0/inst/s00_nodes/s00_r_node/inst/s_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0/inst/s01_nodes/s01_aw_node/inst/s_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0/inst/s01_nodes/s01_b_node/inst/s_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0/inst/s01_nodes/s01_w_node/inst/s_sc_xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0/inst/m00_exit_pipeline/m00_exit/inst/xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0/inst/s00_entry_pipeline/s00_mmu/inst/xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0/inst/s00_entry_pipeline/s00_si_converter/inst/xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0/inst/s00_entry_pipeline/s00_transaction_regulator/inst/xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0/inst/s01_entry_pipeline/s01_mmu/inst/xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0/inst/s01_entry_pipeline/s01_si_converter/inst/xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells smartconnect_0/inst/s01_entry_pipeline/s01_transaction_regulator/inst/xpm_cdc_async_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells axis_data_fifo_0/inst/gen_fifo.xpm_fifo_axis_inst/gaxis_rst_sync.xpm_cdc_sync_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells axis_data_fifo_1/inst/gen_fifo.xpm_fifo_axis_inst/gaxis_rst_sync.xpm_cdc_sync_rst_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells axis_data_fifo_0/inst/gen_fifo.xpm_fifo_axis_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells axis_data_fifo_1/inst/gen_fifo.xpm_fifo_axis_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells axi_dma_0/U0/I_PRMRY_DATAMOVER/GEN_MM2S_FULL.I_MM2S_FULL_WRAPPER/GEN_INCLUDE_MM2S_SF.I_RD_SF/I_DATA_FIFO/BLK_MEM.I_SYNC_FIFOGEN_FIFO/xpm_fifo_instance.xpm_fifo_sync_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells axi_dma_0/U0/I_PRMRY_DATAMOVER/GEN_S2MM_FULL.I_S2MM_FULL_WRAPPER/GEN_ENABLE_INDET_BTT_SF.I_INDET_BTT/I_DATA_FIFO/BLK_MEM.I_SYNC_FIFOGEN_FIFO/xpm_fifo_instance.xpm_fifo_sync_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells axi_dma_0/U0/I_PRMRY_DATAMOVER/GEN_S2MM_FULL.I_S2MM_FULL_WRAPPER/GEN_ENABLE_INDET_BTT_SF.I_INDET_BTT/I_XD_FIFO/NON_BLK_MEM.I_SYNC_FIFOGEN_FIFO/xpm_fifo_instance.xpm_fifo_sync_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {smartconnect_0/inst/m00_nodes/m00_ar_node/inst/inst_mi_handler/gen_normal_area.gen_node_prog_full.inst_node_prog_full/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {smartconnect_0/inst/m00_nodes/m00_aw_node/inst/inst_mi_handler/gen_normal_area.gen_node_prog_full.inst_node_prog_full/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {smartconnect_0/inst/m00_nodes/m00_w_node/inst/inst_mi_handler/gen_normal_area.gen_node_prog_full.inst_node_prog_full/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {smartconnect_0/inst/s00_nodes/s00_r_node/inst/inst_mi_handler/gen_normal_area.gen_node_prog_full.inst_node_prog_full/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {smartconnect_0/inst/s01_nodes/s01_b_node/inst/inst_mi_handler/gen_normal_area.gen_node_prog_full.inst_node_prog_full/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {smartconnect_0/inst/m00_nodes/m00_ar_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {smartconnect_0/inst/m00_nodes/m00_aw_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {smartconnect_0/inst/m00_nodes/m00_b_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {smartconnect_0/inst/m00_nodes/m00_r_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {smartconnect_0/inst/m00_nodes/m00_b_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {smartconnect_0/inst/m00_nodes/m00_r_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {smartconnect_0/inst/m00_nodes/m00_w_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {smartconnect_0/inst/m00_nodes/m00_w_node/inst/inst_si_handler/gen_si_handler.gen_request_fifos.gen_req_fifo[0].inst_req_fifo/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {smartconnect_0/inst/m00_nodes/m00_w_node/inst/inst_si_handler/gen_si_handler.gen_request_fifos.gen_req_fifo[1].inst_req_fifo/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {smartconnect_0/inst/s00_nodes/s00_ar_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {smartconnect_0/inst/s01_nodes/s01_aw_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {smartconnect_0/inst/s01_nodes/s01_w_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {smartconnect_0/inst/s00_nodes/s00_ar_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {smartconnect_0/inst/s01_nodes/s01_aw_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {smartconnect_0/inst/s00_nodes/s00_r_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {smartconnect_0/inst/s01_nodes/s01_b_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {smartconnect_0/inst/s01_nodes/s01_w_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_ita_hwpe_wrap/i_ita/i_engine/i_ita/i_accumulator/partialsum_buffer_sram.i_partialsum_buffer/gen_2_ports.i_xpm_memory_tdpram]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[0].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[10].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[11].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[12].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[13].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[14].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[15].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[16].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[17].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[18].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[19].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[1].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[20].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[21].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[22].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[23].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[24].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[25].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[26].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[27].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[28].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[29].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[2].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[30].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[31].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[3].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[4].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[5].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[6].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[7].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[8].uram_inst}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {ITA_AXI_WRAPPER_0/inst/i_ITA_FPGA_WRAPPER/i_uram_memory_controller_ita_dma/g_uram_instance[9].uram_inst}]
