# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-65511-coppholl/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xck26-sfvc784-2LV-c
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/low_latency_interco
    /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/peripheral_interco
    /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/include
    /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/common
    /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-ctrl-b4d268c729c1adb1/rtl
    /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl
    /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/include/common_cells
    /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl
    /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog
    /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog
    /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl
    /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl
    /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl
  } -define {TARGET_ITA_HWPE TARGET_ITA_HWPE_TEST TARGET_RTL TARGET_SIMULATION TARGET_TEST TARGET_VSIM NO_STALLS=0 SINGLE_ATTENTION=0 ITA_N=8 ITA_M=64 SEQ_LENGTH=64 EMBED_SIZE=128 PROJ_SPACE=192 FF_SIZE=256 BIAS=1 ACTIVATION=Relu HCI_ASSERT_DELAY={#41ps}} {
      /home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/3718/hdl/sc_switchboard_v1_0_vl_rfs.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_2/synth/bd_9be7_arsw_0.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_3/synth/bd_9be7_rsw_0.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_4/synth/bd_9be7_awsw_0.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_5/synth/bd_9be7_wsw_0.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_6/synth/bd_9be7_bsw_0.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/98d8/hdl/sc_mmu_v1_0_vl_rfs.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_7/synth/bd_9be7_s00mmu_0.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/2da8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_8/synth/bd_9be7_s00tr_0.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/a950/hdl/sc_si_converter_v1_0_vl_rfs.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_9/synth/bd_9be7_s00sic_0.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/cef3/hdl/sc_axi2sc_v1_0_vl_rfs.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_10/synth/bd_9be7_s00a2s_0.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/sc_node_v1_0_vl_rfs.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_11/synth/bd_9be7_sarn_0.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_12/synth/bd_9be7_srn_0.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_13/synth/bd_9be7_s01mmu_0.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_14/synth/bd_9be7_s01tr_0.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_15/synth/bd_9be7_s01sic_0.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_16/synth/bd_9be7_s01a2s_0.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_17/synth/bd_9be7_sawn_0.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_18/synth/bd_9be7_swn_0.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_19/synth/bd_9be7_sbn_0.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/7f4f/hdl/sc_sc2axi_v1_0_vl_rfs.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_20/synth/bd_9be7_m00s2a_0.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_21/synth/bd_9be7_m00arn_0.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_22/synth/bd_9be7_m00rn_0.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_23/synth/bd_9be7_m00awn_0.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_24/synth/bd_9be7_m00wn_0.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_25/synth/bd_9be7_m00bn_0.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/1f04/hdl/sc_exit_v1_0_vl_rfs.sv
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_26/synth/bd_9be7_m00e_0.sv
    }
      rt::read_verilog -sv -include {
    /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/low_latency_interco
    /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/peripheral_interco
    /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/include
    /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/common
    /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-ctrl-b4d268c729c1adb1/rtl
    /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl
    /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/include/common_cells
    /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl
    /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog
    /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog
    /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl
    /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl
    /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl
  } -define {TARGET_ITA_HWPE TARGET_ITA_HWPE_TEST TARGET_RTL TARGET_SIMULATION TARGET_TEST TARGET_VSIM NO_STALLS=0 SINGLE_ATTENTION=0 ITA_N=8 ITA_M=64 SEQ_LENGTH=64 EMBED_SIZE=128 PROJ_SPACE=192 FF_SIZE=256 BIAS=1 ACTIVATION=Relu HCI_ASSERT_DELAY={#41ps}} {
      /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/cf_math_pkg.sv
      /home/coppholl/Projects/ITA-FPGA/src/ita_package.sv
      /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/hwpe_stream_package.sv
      /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/common/hci_package.sv
      /home/coppholl/Projects/ITA-FPGA/src/hwpe/ita_hwpe_package.sv
      /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-ctrl-b4d268c729c1adb1/rtl/hwpe_ctrl_package.sv
      /home/coppholl/Projects/ITA-FPGA/ita_kria_wrapper/ITA_FPGA_WRAPPER.sv
      /home/coppholl/Projects/ITA-FPGA/ita_kria_wrapper/dma_address_generator.sv
      /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/fifo_v3.sv
      /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/core/hci_core_assign.sv
      /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/core/hci_core_fifo.sv
      /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/core/hci_core_mux_ooo.sv
      /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/core/hci_core_r_id_filter.sv
      /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/core/hci_core_sink.sv
      /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/core/hci_core_source.sv
      /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/common/hci_interfaces.sv
      /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-ctrl-b4d268c729c1adb1/rtl/hwpe_ctrl_interfaces.sv
      /home/coppholl/Projects/ITA-FPGA/no_latches/hwpe_ctrl_regfile.sv
      /home/coppholl/Projects/ITA-FPGA/no_latches/hwpe_ctrl_regfile_ff.sv
      /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-ctrl-b4d268c729c1adb1/rtl/hwpe_ctrl_regfile_latch.sv
      /home/coppholl/Projects/ITA-FPGA/no_latches/hwpe_ctrl_regfile_latch_test_wrap.sv
      /home/coppholl/Projects/ITA-FPGA/no_latches/hwpe_ctrl_slave.sv
      /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/streamer/hwpe_stream_addressgen_v3.sv
      /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/basic/hwpe_stream_assign.sv
      /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/basic/hwpe_stream_fence.sv
      /home/coppholl/Projects/ITA-FPGA/no_latches/hwpe_stream_fifo.sv
      /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/fifo/hwpe_stream_fifo_passthrough.sv
      /home/coppholl/Projects/ITA-FPGA/no_latches/hwpe_stream_fifo_scm.sv
      /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/fifo/hwpe_stream_fifo_scm_test_wrap.sv
      /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/hwpe_stream_interfaces.sv
      /home/coppholl/Projects/ITA-FPGA/src/ita.sv
      /home/coppholl/Projects/ITA-FPGA/src/ita_accumulator.sv
      /home/coppholl/Projects/ITA-FPGA/src/ita_activation.sv
      /home/coppholl/Projects/ITA-FPGA/src/ita_controller.sv
      /home/coppholl/Projects/ITA-FPGA/src/ita_dotp.sv
      /home/coppholl/Projects/ITA-FPGA/src/ita_fifo_controller.sv
      /home/coppholl/Projects/ITA-FPGA/src/ita_gelu.sv
      /home/coppholl/Projects/ITA-FPGA/src/hwpe/ita_hwpe_ctrl.sv
      /home/coppholl/Projects/ITA-FPGA/src/hwpe/ita_hwpe_engine.sv
      /home/coppholl/Projects/ITA-FPGA/src/hwpe/ita_hwpe_input_bias_buffer.sv
      /home/coppholl/Projects/ITA-FPGA/src/hwpe/ita_hwpe_input_bias_fence.sv
      /home/coppholl/Projects/ITA-FPGA/src/hwpe/ita_hwpe_input_buffer.sv
      /home/coppholl/Projects/ITA-FPGA/src/hwpe/ita_hwpe_output_buffer.sv
      /home/coppholl/Projects/ITA-FPGA/src/hwpe/ita_hwpe_streamer.sv
      /home/coppholl/Projects/ITA-FPGA/src/hwpe/ita_hwpe_top.sv
      /home/coppholl/Projects/ITA-FPGA/src/hwpe/ita_hwpe_wrap.sv
      /home/coppholl/Projects/ITA-FPGA/src/ita_inp1_mux.sv
      /home/coppholl/Projects/ITA-FPGA/src/ita_inp2_mux.sv
      /home/coppholl/Projects/ITA-FPGA/src/ita_input_sampler.sv
      /home/coppholl/Projects/ITA-FPGA/src/ita_max_finder.sv
      /home/coppholl/Projects/ITA-FPGA/src/ita_output_controller.sv
      /home/coppholl/Projects/ITA-FPGA/src/ita_register_file_1w_1r_multiwidth.sv
      /home/coppholl/Projects/ITA-FPGA/src/ita_register_file_1w_multi_port_read.sv
      /home/coppholl/Projects/ITA-FPGA/src/ita_register_file_1w_multi_port_read_we.sv
      /home/coppholl/Projects/ITA-FPGA/src/ita_relu.sv
      /home/coppholl/Projects/ITA-FPGA/src/ita_requantization_controller.sv
      /home/coppholl/Projects/ITA-FPGA/src/ita_requantizer.sv
      /home/coppholl/Projects/ITA-FPGA/ita_kria_wrapper/ita_sequence_qk_step.sv
      /home/coppholl/Projects/ITA-FPGA/ita_kria_wrapper/ita_sequencer_av_step.sv
      /home/coppholl/Projects/ITA-FPGA/ita_kria_wrapper/ita_sequencer_f1_step.sv
      /home/coppholl/Projects/ITA-FPGA/ita_kria_wrapper/ita_sequencer_f2_step.sv
      /home/coppholl/Projects/ITA-FPGA/ita_kria_wrapper/ita_sequencer_k_step.sv
      /home/coppholl/Projects/ITA-FPGA/ita_kria_wrapper/ita_sequencer_ow_step.sv
      /home/coppholl/Projects/ITA-FPGA/ita_kria_wrapper/ita_sequencer_q_step.sv
      /home/coppholl/Projects/ITA-FPGA/ita_kria_wrapper/ita_sequencer_v_step.sv
      /home/coppholl/Projects/ITA-FPGA/src/ita_serdiv.sv
      /home/coppholl/Projects/ITA-FPGA/src/ita_softmax.sv
      /home/coppholl/Projects/ITA-FPGA/src/ita_softmax_top.sv
      /home/coppholl/Projects/ITA-FPGA/src/ita_sumdotp.sv
      /home/coppholl/Projects/ITA-FPGA/src/ita_weight_controller.sv
      /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/lzc.sv
      /home/coppholl/Projects/ITA-FPGA/no_latches/register_file_1r_1w.sv
      /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/scm-a479c2e455a7e638/fpga_scm/register_file_1r_1w_1row.sv
      /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/scm-a479c2e455a7e638/fpga_scm/register_file_1w_multi_port_read.sv
      /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/tech_cells_generic-55fa3871c0dd2458/src/fpga/tc_clk_xilinx.sv
      /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/tech_cells_generic-55fa3871c0dd2458/src/fpga/tc_sram_xilinx.sv
      /home/coppholl/Projects/ITA-FPGA/ita_kria_wrapper/uram_memory_controller_ita_dma.sv
    }
      rt::read_verilog -include {
    /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/low_latency_interco
    /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/peripheral_interco
    /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/include
    /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/common
    /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-ctrl-b4d268c729c1adb1/rtl
    /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl
    /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/include/common_cells
    /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl
    /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog
    /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog
    /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl
    /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl
    /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl
  } -define {TARGET_ITA_HWPE TARGET_ITA_HWPE_TEST TARGET_RTL TARGET_SIMULATION TARGET_TEST TARGET_VSIM NO_STALLS=0 SINGLE_ATTENTION=0 ITA_N=8 ITA_M=64 SEQ_LENGTH=64 EMBED_SIZE=128 PROJ_SPACE=192 FF_SIZE=256 BIAS=1 ACTIVATION=Relu HCI_ASSERT_DELAY={#41ps}} {
      /home/coppholl/Projects/ITA-FPGA/ita_kria_wrapper/ITA_AXI_WRAPPER.v
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/synth/DMA_LED.v
    }
      rt::read_verilog -include {
    /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/low_latency_interco
    /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/peripheral_interco
    /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/include
    /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/common
    /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-ctrl-b4d268c729c1adb1/rtl
    /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl
    /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/include/common_cells
    /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl
    /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog
    /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog
    /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl
    /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl
    /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl
  } -define {TARGET_ITA_HWPE TARGET_ITA_HWPE_TEST TARGET_RTL TARGET_SIMULATION TARGET_TEST TARGET_VSIM NO_STALLS=0 SINGLE_ATTENTION=0 ITA_N=8 ITA_M=64 SEQ_LENGTH=64 EMBED_SIZE=128 PROJ_SPACE=192 FF_SIZE=256 BIAS=1 ACTIVATION=Relu HCI_ASSERT_DELAY={#41ps}} {
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_zynq_ultra_ps_e_0_0/hdl/zynq_ultra_ps_e_v3_5_3.v
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_zynq_ultra_ps_e_0_0/synth/DMA_LED_zynq_ultra_ps_e_0_0.v
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/6120/hdl/xlconcat_v2_1_vl_rfs.v
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_xlconcat_0_0/synth/DMA_LED_xlconcat_0_0.v
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/e2d2/hdl/xlconstant_v1_1_vl_rfs.v
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_0/synth/bd_9be7_one_0.v
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/synth/bd_9be7.v
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/synth/DMA_LED_smartconnect_0_0.v
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/0c28/hdl/generic_baseblocks_v2_1_vl_rfs.v
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/92b2/hdl/axi_register_slice_v2_1_vl_rfs.v
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/9692/hdl/axi_data_fifo_v2_1_vl_rfs.v
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/e9d8/hdl/axi_crossbar_v2_1_vl_rfs.v
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_xbar_0/synth/DMA_LED_xbar_0.v
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/3c06/hdl/axi_protocol_converter_v2_1_vl_rfs.v
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_auto_pc_0/synth/DMA_LED_auto_pc_0.v
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_auto_pc_1/synth/DMA_LED_auto_pc_1.v
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_xlconstant_0_0/synth/DMA_LED_xlconstant_0_0.v
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_xlconstant_1_0/synth/DMA_LED_xlconstant_1_0.v
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a97c/hdl/xlslice_v1_0_vl_rfs.v
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_xlslice_0_0/synth/DMA_LED_xlslice_0_0.v
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl/axis_infrastructure_v1_1_vl_rfs.v
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/2e12/hdl/axis_data_fifo_v2_0_vl_rfs.v
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_axis_data_fifo_0_0/synth/DMA_LED_axis_data_fifo_0_0.v
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_axis_data_fifo_1_0/synth/DMA_LED_axis_data_fifo_1_0.v
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_ITA_AXI_WRAPPER_0_1/synth/DMA_LED_ITA_AXI_WRAPPER_0_1.v
    }
      rt::read_vhdl -lib xpm /home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::read_vhdl -lib lib_pkg_v1_0_4 /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/8c68/hdl/lib_pkg_v1_0_rfs.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_4_8 /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/09bd/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_2_10 /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/1443/hdl/fifo_generator_v13_2_vhsyn_rfs.vhd
      rt::read_vhdl -lib lib_fifo_v1_0_19 /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/0a12/hdl/lib_fifo_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_srl_fifo_v1_0_4 /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/1e5a/hdl/lib_srl_fifo_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_cdc_v1_0_3 /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/2a4f/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib axi_datamover_v5_1_33 /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/bf20/hdl/axi_datamover_v5_1_vh_rfs.vhd
      rt::read_vhdl -lib axi_sg_v4_1_18 /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/6f54/hdl/axi_sg_v4_1_rfs.vhd
      rt::read_vhdl -lib axi_dma_v7_1_32 /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/8830/hdl/axi_dma_v7_1_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_axi_dma_0_0/synth/DMA_LED_axi_dma_0_0.vhd
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_proc_sys_reset_0_0/synth/DMA_LED_proc_sys_reset_0_0.vhd
      /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_1/synth/bd_9be7_psr_aclk_0.vhd
    }
      rt::read_vhdl -lib proc_sys_reset_v5_0_15 /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/3a26/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-65511-coppholl/realtime/DMA_LED_synth.xdc
    rt::sdcChecksum
    set rt::top DMA_LED
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::ioInsertion false
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: out_of_context
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-65511-coppholl/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
