# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.runs/DMA_LED_synth_1/DMA_LED.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "DMA_LED_synth_1" START { ROLLUP_AUTO }
set_param bd.open.in_stealth_mode 1
set_param chipscope.maxJobs 2
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config  -id {17-179}  -suppress 
set_param project.vivado.isBlockSynthRun true
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xck26-sfvc784-2LV-c

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.cache/wt [current_project]
set_property parent.project_path /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kr260_som:part0:1.1 [current_project]
set_property ip_output_repo /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs {
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/low_latency_interco
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/cluster_interconnect-d5833d25198a0133/rtl/peripheral_interco
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/include
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/common
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-ctrl-b4d268c729c1adb1/rtl
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl
} [current_fileset]
set_property verilog_define {TARGET_ITA_HWPE TARGET_ITA_HWPE_TEST TARGET_RTL TARGET_SIMULATION TARGET_TEST TARGET_VSIM NO_STALLS=0 SINGLE_ATTENTION=0 ITA_N=8 ITA_M=64 SEQ_LENGTH=64 EMBED_SIZE=128 PROJ_SPACE=192 FF_SIZE=256 BIAS=1 ACTIVATION=Relu HCI_ASSERT_DELAY=#41ps} [current_fileset]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/common/hci_helpers.svh
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/include/common_cells/assertions.svh
}
set_property file_type "Verilog Header" [get_files /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/common/hci_helpers.svh]
set_property file_type "Verilog Header" [get_files /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/include/common_cells/assertions.svh]
read_verilog -library xil_defaultlib -sv {
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/cf_math_pkg.sv
  /home/coppholl/Projects/ITA-FPGA/src/ita_package.sv
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/hwpe_stream_package.sv
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/common/hci_package.sv
  /home/coppholl/Projects/ITA-FPGA/src/hwpe/ita_hwpe_package.sv
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-ctrl-b4d268c729c1adb1/rtl/hwpe_ctrl_package.sv
  /home/coppholl/Projects/ITA-FPGA/ita_kria_wrapper/ITA_FPGA_WRAPPER.sv
  /home/coppholl/Projects/ITA-FPGA/ita_kria_wrapper/dma_address_generator.sv
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/fifo_v3.sv
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/core/hci_core_assign.sv
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/core/hci_core_fifo.sv
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/core/hci_core_mux_ooo.sv
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/core/hci_core_r_id_filter.sv
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/core/hci_core_sink.sv
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/core/hci_core_source.sv
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hci-5c5dd55394261a4b/rtl/common/hci_interfaces.sv
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-ctrl-b4d268c729c1adb1/rtl/hwpe_ctrl_interfaces.sv
  /home/coppholl/Projects/ITA-FPGA/no_latches/hwpe_ctrl_regfile.sv
  /home/coppholl/Projects/ITA-FPGA/no_latches/hwpe_ctrl_regfile_ff.sv
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-ctrl-b4d268c729c1adb1/rtl/hwpe_ctrl_regfile_latch.sv
  /home/coppholl/Projects/ITA-FPGA/no_latches/hwpe_ctrl_regfile_latch_test_wrap.sv
  /home/coppholl/Projects/ITA-FPGA/no_latches/hwpe_ctrl_slave.sv
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/streamer/hwpe_stream_addressgen_v3.sv
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/basic/hwpe_stream_assign.sv
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/basic/hwpe_stream_fence.sv
  /home/coppholl/Projects/ITA-FPGA/no_latches/hwpe_stream_fifo.sv
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/fifo/hwpe_stream_fifo_passthrough.sv
  /home/coppholl/Projects/ITA-FPGA/no_latches/hwpe_stream_fifo_scm.sv
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/fifo/hwpe_stream_fifo_scm_test_wrap.sv
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/hwpe-stream-5514f8f76c0edc16/rtl/hwpe_stream_interfaces.sv
  /home/coppholl/Projects/ITA-FPGA/src/ita.sv
  /home/coppholl/Projects/ITA-FPGA/src/ita_accumulator.sv
  /home/coppholl/Projects/ITA-FPGA/src/ita_activation.sv
  /home/coppholl/Projects/ITA-FPGA/src/ita_controller.sv
  /home/coppholl/Projects/ITA-FPGA/src/ita_dotp.sv
  /home/coppholl/Projects/ITA-FPGA/src/ita_fifo_controller.sv
  /home/coppholl/Projects/ITA-FPGA/src/ita_gelu.sv
  /home/coppholl/Projects/ITA-FPGA/src/hwpe/ita_hwpe_ctrl.sv
  /home/coppholl/Projects/ITA-FPGA/src/hwpe/ita_hwpe_engine.sv
  /home/coppholl/Projects/ITA-FPGA/src/hwpe/ita_hwpe_input_bias_buffer.sv
  /home/coppholl/Projects/ITA-FPGA/src/hwpe/ita_hwpe_input_bias_fence.sv
  /home/coppholl/Projects/ITA-FPGA/src/hwpe/ita_hwpe_input_buffer.sv
  /home/coppholl/Projects/ITA-FPGA/src/hwpe/ita_hwpe_output_buffer.sv
  /home/coppholl/Projects/ITA-FPGA/src/hwpe/ita_hwpe_streamer.sv
  /home/coppholl/Projects/ITA-FPGA/src/hwpe/ita_hwpe_top.sv
  /home/coppholl/Projects/ITA-FPGA/src/hwpe/ita_hwpe_wrap.sv
  /home/coppholl/Projects/ITA-FPGA/src/ita_inp1_mux.sv
  /home/coppholl/Projects/ITA-FPGA/src/ita_inp2_mux.sv
  /home/coppholl/Projects/ITA-FPGA/src/ita_input_sampler.sv
  /home/coppholl/Projects/ITA-FPGA/src/ita_max_finder.sv
  /home/coppholl/Projects/ITA-FPGA/src/ita_output_controller.sv
  /home/coppholl/Projects/ITA-FPGA/src/ita_register_file_1w_1r_multiwidth.sv
  /home/coppholl/Projects/ITA-FPGA/src/ita_register_file_1w_multi_port_read.sv
  /home/coppholl/Projects/ITA-FPGA/src/ita_register_file_1w_multi_port_read_we.sv
  /home/coppholl/Projects/ITA-FPGA/src/ita_relu.sv
  /home/coppholl/Projects/ITA-FPGA/src/ita_requantization_controller.sv
  /home/coppholl/Projects/ITA-FPGA/src/ita_requantizer.sv
  /home/coppholl/Projects/ITA-FPGA/ita_kria_wrapper/ita_sequence_qk_step.sv
  /home/coppholl/Projects/ITA-FPGA/ita_kria_wrapper/ita_sequencer_av_step.sv
  /home/coppholl/Projects/ITA-FPGA/ita_kria_wrapper/ita_sequencer_f1_step.sv
  /home/coppholl/Projects/ITA-FPGA/ita_kria_wrapper/ita_sequencer_f2_step.sv
  /home/coppholl/Projects/ITA-FPGA/ita_kria_wrapper/ita_sequencer_k_step.sv
  /home/coppholl/Projects/ITA-FPGA/ita_kria_wrapper/ita_sequencer_ow_step.sv
  /home/coppholl/Projects/ITA-FPGA/ita_kria_wrapper/ita_sequencer_q_step.sv
  /home/coppholl/Projects/ITA-FPGA/ita_kria_wrapper/ita_sequencer_v_step.sv
  /home/coppholl/Projects/ITA-FPGA/src/ita_serdiv.sv
  /home/coppholl/Projects/ITA-FPGA/src/ita_softmax.sv
  /home/coppholl/Projects/ITA-FPGA/src/ita_softmax_top.sv
  /home/coppholl/Projects/ITA-FPGA/src/ita_sumdotp.sv
  /home/coppholl/Projects/ITA-FPGA/src/ita_weight_controller.sv
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/common_cells-a9dda427ecf0aef2/src/lzc.sv
  /home/coppholl/Projects/ITA-FPGA/no_latches/register_file_1r_1w.sv
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/scm-a479c2e455a7e638/fpga_scm/register_file_1r_1w_1row.sv
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/scm-a479c2e455a7e638/fpga_scm/register_file_1w_multi_port_read.sv
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/tech_cells_generic-55fa3871c0dd2458/src/fpga/tc_clk_xilinx.sv
  /home/coppholl/Projects/ITA-FPGA/.bender/git/checkouts/tech_cells_generic-55fa3871c0dd2458/src/fpga/tc_sram_xilinx.sv
  /home/coppholl/Projects/ITA-FPGA/ita_kria_wrapper/uram_memory_controller_ita_dma.sv
}
read_verilog -library xil_defaultlib /home/coppholl/Projects/ITA-FPGA/ita_kria_wrapper/ITA_AXI_WRAPPER.v
add_files /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/DMA_LED.bd
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_zynq_ultra_ps_e_0_0/DMA_LED_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_zynq_ultra_ps_e_0_0/DMA_LED_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_axi_dma_0_0/DMA_LED_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_axi_dma_0_0/DMA_LED_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_proc_sys_reset_0_0/DMA_LED_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_proc_sys_reset_0_0/DMA_LED_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_1/bd_9be7_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_1/bd_9be7_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_2/bd_9be7_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_3/bd_9be7_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_4/bd_9be7_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_5/bd_9be7_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_6/bd_9be7_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_10/bd_9be7_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_11/bd_9be7_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_11/bd_9be7_sarn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_12/bd_9be7_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_12/bd_9be7_srn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_16/bd_9be7_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_17/bd_9be7_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_17/bd_9be7_sawn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_18/bd_9be7_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_18/bd_9be7_swn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_19/bd_9be7_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_19/bd_9be7_sbn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_20/bd_9be7_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_21/bd_9be7_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_21/bd_9be7_m00arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_22/bd_9be7_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_22/bd_9be7_m00rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_23/bd_9be7_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_23/bd_9be7_m00awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_24/bd_9be7_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_24/bd_9be7_m00wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_25/bd_9be7_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_25/bd_9be7_m00bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_auto_pc_0/DMA_LED_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_auto_pc_1/DMA_LED_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/DMA_LED_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top DMA_LED -part xck26-sfvc784-2LV-c -incremental_mode off -mode out_of_context
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}

rename_ref -prefix_all DMA_LED_

OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef DMA_LED.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file DMA_LED_utilization_synth.rpt -pb DMA_LED_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }

if { [catch {
  file copy -force /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.runs/DMA_LED_synth_1/DMA_LED.dcp /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/DMA_LED.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 status "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/DMA_LED_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/DMA_LED_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/DMA_LED_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/DMA_LED_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.ip_user_files/bd/DMA_LED]} {
  catch { 
    file copy -force /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/DMA_LED_stub.v /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.ip_user_files/bd/DMA_LED
  }
}

if {[file isdir /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.ip_user_files/bd/DMA_LED]} {
  catch { 
    file copy -force /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/DMA_LED_stub.vhdl /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.ip_user_files/bd/DMA_LED
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "DMA_LED_synth_1" END { }
