# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/DMA_LED.bd
# Block Designs: The module: 'DMA_LED' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_zynq_ultra_ps_e_0_0/DMA_LED_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==DMA_LED_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_axi_dma_0_0/DMA_LED_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_axi_dma_0_0 || ORIG_REF_NAME==DMA_LED_axi_dma_0_0} -quiet] -quiet

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_proc_sys_reset_0_0/DMA_LED_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_proc_sys_reset_0_0 || ORIG_REF_NAME==DMA_LED_proc_sys_reset_0_0} -quiet] -quiet

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_xlconcat_0_0/DMA_LED_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_xlconcat_0_0 || ORIG_REF_NAME==DMA_LED_xlconcat_0_0} -quiet] -quiet

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/DMA_LED_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_smartconnect_0_0 || ORIG_REF_NAME==DMA_LED_smartconnect_0_0} -quiet] -quiet

# Block Designs: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/bd_9be7.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_0/bd_9be7_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_1/bd_9be7_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_2/bd_9be7_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_3/bd_9be7_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_4/bd_9be7_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_5/bd_9be7_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_6/bd_9be7_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_7/bd_9be7_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_8/bd_9be7_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_9/bd_9be7_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_10/bd_9be7_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_11/bd_9be7_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_12/bd_9be7_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_13/bd_9be7_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_14/bd_9be7_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_15/bd_9be7_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_16/bd_9be7_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_17/bd_9be7_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_18/bd_9be7_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_19/bd_9be7_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_20/bd_9be7_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_21/bd_9be7_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_22/bd_9be7_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_23/bd_9be7_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_24/bd_9be7_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_25/bd_9be7_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_26/bd_9be7_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_xbar_0/DMA_LED_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_xbar_0 || ORIG_REF_NAME==DMA_LED_xbar_0} -quiet] -quiet

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_axi_interconnect_0_0/DMA_LED_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_axi_interconnect_0_0 || ORIG_REF_NAME==DMA_LED_axi_interconnect_0_0} -quiet] -quiet

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_xlconstant_0_0/DMA_LED_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_xlconstant_0_0 || ORIG_REF_NAME==DMA_LED_xlconstant_0_0} -quiet] -quiet

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_xlconstant_1_0/DMA_LED_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_xlconstant_1_0 || ORIG_REF_NAME==DMA_LED_xlconstant_1_0} -quiet] -quiet

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_xlslice_0_0/DMA_LED_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_xlslice_0_0 || ORIG_REF_NAME==DMA_LED_xlslice_0_0} -quiet] -quiet

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_axis_data_fifo_0_0/DMA_LED_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_axis_data_fifo_0_0 || ORIG_REF_NAME==DMA_LED_axis_data_fifo_0_0} -quiet] -quiet

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_axis_data_fifo_1_0/DMA_LED_axis_data_fifo_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_axis_data_fifo_1_0 || ORIG_REF_NAME==DMA_LED_axis_data_fifo_1_0} -quiet] -quiet

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_ITA_AXI_WRAPPER_0_1/DMA_LED_ITA_AXI_WRAPPER_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_ITA_AXI_WRAPPER_0_1 || ORIG_REF_NAME==DMA_LED_ITA_AXI_WRAPPER_0_1} -quiet] -quiet

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_auto_pc_0/DMA_LED_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_auto_pc_0 || ORIG_REF_NAME==DMA_LED_auto_pc_0} -quiet] -quiet

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_auto_pc_1/DMA_LED_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_auto_pc_1 || ORIG_REF_NAME==DMA_LED_auto_pc_1} -quiet] -quiet

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_zynq_ultra_ps_e_0_0/DMA_LED_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_zynq_ultra_ps_e_0_0/DMA_LED_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DMA_LED_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==DMA_LED_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_axi_dma_0_0/DMA_LED_axi_dma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DMA_LED_axi_dma_0_0 || ORIG_REF_NAME==DMA_LED_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_axi_dma_0_0/DMA_LED_axi_dma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DMA_LED_axi_dma_0_0 || ORIG_REF_NAME==DMA_LED_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_proc_sys_reset_0_0/DMA_LED_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DMA_LED_proc_sys_reset_0_0 || ORIG_REF_NAME==DMA_LED_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_proc_sys_reset_0_0/DMA_LED_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DMA_LED_proc_sys_reset_0_0 || ORIG_REF_NAME==DMA_LED_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_1/bd_9be7_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_1/bd_9be7_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_2/bd_9be7_arsw_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_3/bd_9be7_rsw_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_4/bd_9be7_awsw_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_5/bd_9be7_wsw_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_6/bd_9be7_bsw_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_10/bd_9be7_s00a2s_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_11/bd_9be7_sarn_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_11/bd_9be7_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_12/bd_9be7_srn_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_12/bd_9be7_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_16/bd_9be7_s01a2s_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_17/bd_9be7_sawn_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_17/bd_9be7_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_18/bd_9be7_swn_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_18/bd_9be7_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_19/bd_9be7_sbn_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_19/bd_9be7_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_20/bd_9be7_m00s2a_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_21/bd_9be7_m00arn_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_21/bd_9be7_m00arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_22/bd_9be7_m00rn_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_22/bd_9be7_m00rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_23/bd_9be7_m00awn_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_23/bd_9be7_m00awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_24/bd_9be7_m00wn_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_24/bd_9be7_m00wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_25/bd_9be7_m00bn_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_25/bd_9be7_m00bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DMA_LED_smartconnect_0_0 || ORIG_REF_NAME==DMA_LED_smartconnect_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_auto_pc_0/DMA_LED_auto_pc_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_auto_pc_1/DMA_LED_auto_pc_1_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/DMA_LED_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DMA_LED'. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/DMA_LED.bd
# Block Designs: The module: 'DMA_LED' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_zynq_ultra_ps_e_0_0/DMA_LED_zynq_ultra_ps_e_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==DMA_LED_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_axi_dma_0_0/DMA_LED_axi_dma_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_axi_dma_0_0 || ORIG_REF_NAME==DMA_LED_axi_dma_0_0} -quiet] -quiet

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_proc_sys_reset_0_0/DMA_LED_proc_sys_reset_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_proc_sys_reset_0_0 || ORIG_REF_NAME==DMA_LED_proc_sys_reset_0_0} -quiet] -quiet

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_xlconcat_0_0/DMA_LED_xlconcat_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_xlconcat_0_0 || ORIG_REF_NAME==DMA_LED_xlconcat_0_0} -quiet] -quiet

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/DMA_LED_smartconnect_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_smartconnect_0_0 || ORIG_REF_NAME==DMA_LED_smartconnect_0_0} -quiet] -quiet

# Block Designs: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/bd_9be7.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_0/bd_9be7_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_1/bd_9be7_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_2/bd_9be7_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_3/bd_9be7_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_4/bd_9be7_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_5/bd_9be7_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_6/bd_9be7_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_7/bd_9be7_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_8/bd_9be7_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_9/bd_9be7_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_10/bd_9be7_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_11/bd_9be7_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_12/bd_9be7_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_13/bd_9be7_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_14/bd_9be7_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_15/bd_9be7_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_16/bd_9be7_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_17/bd_9be7_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_18/bd_9be7_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_19/bd_9be7_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_20/bd_9be7_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_21/bd_9be7_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_22/bd_9be7_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_23/bd_9be7_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_24/bd_9be7_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_25/bd_9be7_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_26/bd_9be7_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_xbar_0/DMA_LED_xbar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_xbar_0 || ORIG_REF_NAME==DMA_LED_xbar_0} -quiet] -quiet

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_axi_interconnect_0_0/DMA_LED_axi_interconnect_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_axi_interconnect_0_0 || ORIG_REF_NAME==DMA_LED_axi_interconnect_0_0} -quiet] -quiet

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_xlconstant_0_0/DMA_LED_xlconstant_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_xlconstant_0_0 || ORIG_REF_NAME==DMA_LED_xlconstant_0_0} -quiet] -quiet

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_xlconstant_1_0/DMA_LED_xlconstant_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_xlconstant_1_0 || ORIG_REF_NAME==DMA_LED_xlconstant_1_0} -quiet] -quiet

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_xlslice_0_0/DMA_LED_xlslice_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_xlslice_0_0 || ORIG_REF_NAME==DMA_LED_xlslice_0_0} -quiet] -quiet

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_axis_data_fifo_0_0/DMA_LED_axis_data_fifo_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_axis_data_fifo_0_0 || ORIG_REF_NAME==DMA_LED_axis_data_fifo_0_0} -quiet] -quiet

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_axis_data_fifo_1_0/DMA_LED_axis_data_fifo_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_axis_data_fifo_1_0 || ORIG_REF_NAME==DMA_LED_axis_data_fifo_1_0} -quiet] -quiet

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_ITA_AXI_WRAPPER_0_1/DMA_LED_ITA_AXI_WRAPPER_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_ITA_AXI_WRAPPER_0_1 || ORIG_REF_NAME==DMA_LED_ITA_AXI_WRAPPER_0_1} -quiet] -quiet

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_auto_pc_0/DMA_LED_auto_pc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_auto_pc_0 || ORIG_REF_NAME==DMA_LED_auto_pc_0} -quiet] -quiet

# IP: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ip/DMA_LED_auto_pc_1/DMA_LED_auto_pc_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DMA_LED_auto_pc_1 || ORIG_REF_NAME==DMA_LED_auto_pc_1} -quiet] -quiet

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_zynq_ultra_ps_e_0_0/DMA_LED_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_zynq_ultra_ps_e_0_0/DMA_LED_zynq_ultra_ps_e_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DMA_LED_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==DMA_LED_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_axi_dma_0_0/DMA_LED_axi_dma_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DMA_LED_axi_dma_0_0 || ORIG_REF_NAME==DMA_LED_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_axi_dma_0_0/DMA_LED_axi_dma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DMA_LED_axi_dma_0_0 || ORIG_REF_NAME==DMA_LED_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_proc_sys_reset_0_0/DMA_LED_proc_sys_reset_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DMA_LED_proc_sys_reset_0_0 || ORIG_REF_NAME==DMA_LED_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_proc_sys_reset_0_0/DMA_LED_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DMA_LED_proc_sys_reset_0_0 || ORIG_REF_NAME==DMA_LED_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_1/bd_9be7_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_1/bd_9be7_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_2/bd_9be7_arsw_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_3/bd_9be7_rsw_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_4/bd_9be7_awsw_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_5/bd_9be7_wsw_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_6/bd_9be7_bsw_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_10/bd_9be7_s00a2s_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_11/bd_9be7_sarn_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_11/bd_9be7_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_12/bd_9be7_srn_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_12/bd_9be7_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_16/bd_9be7_s01a2s_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_17/bd_9be7_sawn_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_17/bd_9be7_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_18/bd_9be7_swn_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_18/bd_9be7_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_19/bd_9be7_sbn_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_19/bd_9be7_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_20/bd_9be7_m00s2a_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_21/bd_9be7_m00arn_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_21/bd_9be7_m00arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_22/bd_9be7_m00rn_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_22/bd_9be7_m00rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_23/bd_9be7_m00awn_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_23/bd_9be7_m00awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_24/bd_9be7_m00wn_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_24/bd_9be7_m00wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_25/bd_9be7_m00bn_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_25/bd_9be7_m00bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/smartconnect.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DMA_LED_smartconnect_0_0 || ORIG_REF_NAME==DMA_LED_smartconnect_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_auto_pc_0/DMA_LED_auto_pc_0_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ip/DMA_LED_auto_pc_1/DMA_LED_auto_pc_1_ooc.xdc

# XDC: /home/coppholl/Projects/ITA-FPGA/ITA-kria-vivado/ITA-kria-vivado.gen/sources_1/bd/DMA_LED/DMA_LED_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DMA_LED'. Do not add the DONT_TOUCH constraint.
