transcript off
onbreak {quit -force}
onerror {quit -force}
transcript on

vlib work
vlib riviera/xilinx_vip
vlib riviera/xpm
vlib riviera/axi_infrastructure_v1_1_0
vlib riviera/axi_vip_v1_1_17
vlib riviera/zynq_ultra_ps_e_vip_v1_0_17
vlib riviera/xil_defaultlib
vlib riviera/lib_pkg_v1_0_4
vlib riviera/fifo_generator_v13_2_10
vlib riviera/lib_fifo_v1_0_19
vlib riviera/lib_srl_fifo_v1_0_4
vlib riviera/lib_cdc_v1_0_3
vlib riviera/axi_datamover_v5_1_33
vlib riviera/axi_sg_v4_1_18
vlib riviera/axi_dma_v7_1_32
vlib riviera/proc_sys_reset_v5_0_15
vlib riviera/xlconcat_v2_1_6
vlib riviera/xlconstant_v1_1_9
vlib riviera/smartconnect_v1_0
vlib riviera/axi_register_slice_v2_1_31
vlib riviera/generic_baseblocks_v2_1_2
vlib riviera/axi_data_fifo_v2_1_30
vlib riviera/axi_crossbar_v2_1_32
vlib riviera/xlslice_v1_0_4
vlib riviera/axis_infrastructure_v1_1_1
vlib riviera/axis_data_fifo_v2_0_13
vlib riviera/axi_protocol_converter_v2_1_31

vmap xilinx_vip riviera/xilinx_vip
vmap xpm riviera/xpm
vmap axi_infrastructure_v1_1_0 riviera/axi_infrastructure_v1_1_0
vmap axi_vip_v1_1_17 riviera/axi_vip_v1_1_17
vmap zynq_ultra_ps_e_vip_v1_0_17 riviera/zynq_ultra_ps_e_vip_v1_0_17
vmap xil_defaultlib riviera/xil_defaultlib
vmap lib_pkg_v1_0_4 riviera/lib_pkg_v1_0_4
vmap fifo_generator_v13_2_10 riviera/fifo_generator_v13_2_10
vmap lib_fifo_v1_0_19 riviera/lib_fifo_v1_0_19
vmap lib_srl_fifo_v1_0_4 riviera/lib_srl_fifo_v1_0_4
vmap lib_cdc_v1_0_3 riviera/lib_cdc_v1_0_3
vmap axi_datamover_v5_1_33 riviera/axi_datamover_v5_1_33
vmap axi_sg_v4_1_18 riviera/axi_sg_v4_1_18
vmap axi_dma_v7_1_32 riviera/axi_dma_v7_1_32
vmap proc_sys_reset_v5_0_15 riviera/proc_sys_reset_v5_0_15
vmap xlconcat_v2_1_6 riviera/xlconcat_v2_1_6
vmap xlconstant_v1_1_9 riviera/xlconstant_v1_1_9
vmap smartconnect_v1_0 riviera/smartconnect_v1_0
vmap axi_register_slice_v2_1_31 riviera/axi_register_slice_v2_1_31
vmap generic_baseblocks_v2_1_2 riviera/generic_baseblocks_v2_1_2
vmap axi_data_fifo_v2_1_30 riviera/axi_data_fifo_v2_1_30
vmap axi_crossbar_v2_1_32 riviera/axi_crossbar_v2_1_32
vmap xlslice_v1_0_4 riviera/xlslice_v1_0_4
vmap axis_infrastructure_v1_1_1 riviera/axis_infrastructure_v1_1_1
vmap axis_data_fifo_v2_0_13 riviera/axis_data_fifo_v2_0_13
vmap axi_protocol_converter_v2_1_31 riviera/axi_protocol_converter_v2_1_31

vlog -work xilinx_vip  -incr  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
"/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
"/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xpm  -incr  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -93  -incr \
"/home/coppholl/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work axi_infrastructure_v1_1_0  -incr -v2k5  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi_vip_v1_1_17  -incr  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/4d04/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work zynq_ultra_ps_e_vip_v1_0_17  -incr  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -v2k5  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../bd/DMA_LED/ip/DMA_LED_zynq_ultra_ps_e_0_0/sim/DMA_LED_zynq_ultra_ps_e_0_0_vip_wrapper.v" \

vcom -work lib_pkg_v1_0_4 -93  -incr \
"../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/8c68/hdl/lib_pkg_v1_0_rfs.vhd" \

vlog -work fifo_generator_v13_2_10  -incr -v2k5  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/1443/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_2_10 -93  -incr \
"../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/1443/hdl/fifo_generator_v13_2_rfs.vhd" \

vlog -work fifo_generator_v13_2_10  -incr -v2k5  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/1443/hdl/fifo_generator_v13_2_rfs.v" \

vcom -work lib_fifo_v1_0_19 -93  -incr \
"../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/0a12/hdl/lib_fifo_v1_0_rfs.vhd" \

vcom -work lib_srl_fifo_v1_0_4 -93  -incr \
"../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/1e5a/hdl/lib_srl_fifo_v1_0_rfs.vhd" \

vcom -work lib_cdc_v1_0_3 -93  -incr \
"../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/2a4f/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work axi_datamover_v5_1_33 -93  -incr \
"../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/bf20/hdl/axi_datamover_v5_1_vh_rfs.vhd" \

vcom -work axi_sg_v4_1_18 -93  -incr \
"../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/6f54/hdl/axi_sg_v4_1_rfs.vhd" \

vcom -work axi_dma_v7_1_32 -93  -incr \
"../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/8830/hdl/axi_dma_v7_1_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/DMA_LED/ip/DMA_LED_axi_dma_0_0/sim/DMA_LED_axi_dma_0_0.vhd" \

vcom -work proc_sys_reset_v5_0_15 -93  -incr \
"../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/3a26/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/DMA_LED/ip/DMA_LED_proc_sys_reset_0_0/sim/DMA_LED_proc_sys_reset_0_0.vhd" \

vlog -work xlconcat_v2_1_6  -incr -v2k5  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/6120/hdl/xlconcat_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../bd/DMA_LED/ip/DMA_LED_xlconcat_0_0/sim/DMA_LED_xlconcat_0_0.v" \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/sim/bd_9be7.v" \

vlog -work xlconstant_v1_1_9  -incr -v2k5  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/e2d2/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_0/sim/bd_9be7_one_0.v" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_1/sim/bd_9be7_psr_aclk_0.vhd" \

vlog -work smartconnect_v1_0  -incr  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
"../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/3718/hdl/sc_switchboard_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_2/sim/bd_9be7_arsw_0.sv" \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_3/sim/bd_9be7_rsw_0.sv" \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_4/sim/bd_9be7_awsw_0.sv" \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_5/sim/bd_9be7_wsw_0.sv" \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_6/sim/bd_9be7_bsw_0.sv" \

vlog -work smartconnect_v1_0  -incr  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/98d8/hdl/sc_mmu_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_7/sim/bd_9be7_s00mmu_0.sv" \

vlog -work smartconnect_v1_0  -incr  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/2da8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_8/sim/bd_9be7_s00tr_0.sv" \

vlog -work smartconnect_v1_0  -incr  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/a950/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_9/sim/bd_9be7_s00sic_0.sv" \

vlog -work smartconnect_v1_0  -incr  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/cef3/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_10/sim/bd_9be7_s00a2s_0.sv" \

vlog -work smartconnect_v1_0  -incr  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/sc_node_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_11/sim/bd_9be7_sarn_0.sv" \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_12/sim/bd_9be7_srn_0.sv" \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_13/sim/bd_9be7_s01mmu_0.sv" \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_14/sim/bd_9be7_s01tr_0.sv" \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_15/sim/bd_9be7_s01sic_0.sv" \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_16/sim/bd_9be7_s01a2s_0.sv" \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_17/sim/bd_9be7_sawn_0.sv" \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_18/sim/bd_9be7_swn_0.sv" \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_19/sim/bd_9be7_sbn_0.sv" \

vlog -work smartconnect_v1_0  -incr  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/7f4f/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_20/sim/bd_9be7_m00s2a_0.sv" \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_21/sim/bd_9be7_m00arn_0.sv" \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_22/sim/bd_9be7_m00rn_0.sv" \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_23/sim/bd_9be7_m00awn_0.sv" \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_24/sim/bd_9be7_m00wn_0.sv" \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_25/sim/bd_9be7_m00bn_0.sv" \

vlog -work smartconnect_v1_0  -incr  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/1f04/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/bd_0/ip/ip_26/sim/bd_9be7_m00e_0.sv" \

vlog -work axi_register_slice_v2_1_31  -incr -v2k5  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/92b2/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../bd/DMA_LED/ip/DMA_LED_smartconnect_0_0/sim/DMA_LED_smartconnect_0_0.v" \

vlog -work generic_baseblocks_v2_1_2  -incr -v2k5  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/0c28/hdl/generic_baseblocks_v2_1_vl_rfs.v" \

vlog -work axi_data_fifo_v2_1_30  -incr -v2k5  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/9692/hdl/axi_data_fifo_v2_1_vl_rfs.v" \

vlog -work axi_crossbar_v2_1_32  -incr -v2k5  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/e9d8/hdl/axi_crossbar_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../bd/DMA_LED/ip/DMA_LED_xbar_0/sim/DMA_LED_xbar_0.v" \
"../../../bd/DMA_LED/ip/DMA_LED_xlconstant_0_0/sim/DMA_LED_xlconstant_0_0.v" \
"../../../bd/DMA_LED/ip/DMA_LED_xlconstant_1_0/sim/DMA_LED_xlconstant_1_0.v" \

vlog -work xlslice_v1_0_4  -incr -v2k5  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a97c/hdl/xlslice_v1_0_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../bd/DMA_LED/ip/DMA_LED_xlslice_0_0/sim/DMA_LED_xlslice_0_0.v" \

vlog -work axis_infrastructure_v1_1_1  -incr -v2k5  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl/axis_infrastructure_v1_1_vl_rfs.v" \

vlog -work axis_data_fifo_v2_0_13  -incr -v2k5  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/2e12/hdl/axis_data_fifo_v2_0_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../bd/DMA_LED/ip/DMA_LED_axis_data_fifo_0_0/sim/DMA_LED_axis_data_fifo_0_0.v" \
"../../../bd/DMA_LED/ip/DMA_LED_axis_data_fifo_1_0/sim/DMA_LED_axis_data_fifo_1_0.v" \
"../../../bd/DMA_LED/ip/DMA_LED_ITA_AXI_WRAPPER_0_1/sim/DMA_LED_ITA_AXI_WRAPPER_0_1.v" \

vlog -work axi_protocol_converter_v2_1_31  -incr -v2k5  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/3c06/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5  +define+TARGET_ITA_HWPE=  +define+TARGET_ITA_HWPE_TEST=  +define+TARGET_RTL=  +define+TARGET_SIMULATION=  +define+TARGET_TEST=  +define+TARGET_VSIM=  +define+NO_STALLS=0  +define+SINGLE_ATTENTION=0  +define+ITA_N=8  +define+ITA_M=64  +define+SEQ_LENGTH=64  +define+EMBED_SIZE=128  +define+PROJ_SPACE=192  +define+FF_SIZE=256  +define+BIAS=1  +define+ACTIVATION=Relu  +define+HCI_ASSERT_DELAY=#41ps "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/a317/hdl" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/434f/hdl" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.gen/sources_1/bd/DMA_LED/ipshared/c783/hdl/verilog" "+incdir+../../../../ITA-kria-vivado.srcs/sources_1/bd/DMA_LED/ipshared/ec67/hdl" "+incdir+/home/coppholl/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l zynq_ultra_ps_e_vip_v1_0_17 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_10 -l lib_fifo_v1_0_19 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_33 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l proc_sys_reset_v5_0_15 -l xlconcat_v2_1_6 -l xlconstant_v1_1_9 -l smartconnect_v1_0 -l axi_register_slice_v2_1_31 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l xlslice_v1_0_4 -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_13 -l axi_protocol_converter_v2_1_31 \
"../../../bd/DMA_LED/ip/DMA_LED_auto_pc_0/sim/DMA_LED_auto_pc_0.v" \
"../../../bd/DMA_LED/ip/DMA_LED_auto_pc_1/sim/DMA_LED_auto_pc_1.v" \
"../../../bd/DMA_LED/sim/DMA_LED.v" \

vlog -work xil_defaultlib \
"glbl.v"

